// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace WebAppTestMovieEF.Models;

public partial class CorsoAcademyContext : DbContext
{
    public CorsoAcademyContext()
    {
    }

    public CorsoAcademyContext(DbContextOptions<CorsoAcademyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TGenre> TGenres { get; set; }

    public virtual DbSet<TMovie> TMovies { get; set; }

    public virtual DbSet<TSpinoff> TSpinoffs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        // => optionsBuilder.UseSqlServer("Data Source=PCLAB-112\\MSSQLSERVER01;Initial Catalog=CorsoAcademy;Integrated Security=False;User=CorsoAcademy;Password=CorsoAcademy01!;TrustServerCertificate=Yes;");
        => optionsBuilder.UseSqlServer("Data Source=FRANCESCO;Initial Catalog=CorsoAcademy;Integrated Security=False;User=CorsoAcademy;Password=CorsoAcademy01!;TrustServerCertificate=Yes;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TMovie>(entity =>
        {
            entity.HasOne(d => d.IdGenreNavigation).WithMany(p => p.TMovies).HasConstraintName("FK_T_Movie_T_Genre");
        });

        modelBuilder.Entity<TSpinoff>(entity =>
        {
            entity.HasOne(d => d.IdMovieNavigation).WithMany(p => p.TSpinoffs).HasConstraintName("FK_T_Spinoff_T_Movie");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}