// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppTestMovieEF.Models;

[Table("T_Genre")]
public partial class TGenre
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Genere { get; set; }

    [Column("isAdult")]
    [Display(Name = "Per Adulti")]
    public bool? IsAdult { get; set; }

    [InverseProperty("IdGenreNavigation")]
    public virtual ICollection<TMovie> TMovies { get; set; } = new List<TMovie>();
}