// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppTestMovieEF.Models;

[Table("T_Movie")]
public partial class TMovie
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Film { get; set; }

    public DateOnly? Data { get; set; }

    [Column("isAdult")]
    [Display(Name = "Per Adulti")]
    public bool? IsAdult { get; set; }

    [Column("idGenre")]
    [Display(Name = "Genere")]
    public int? IdGenre { get; set; }

    [ForeignKey("IdGenre")]
    [InverseProperty("TMovies")]
    [Display(Name = "Genere di Appartenenza")]

    public virtual TGenre IdGenreNavigation { get; set; }

    [InverseProperty("IdMovieNavigation")]
    public virtual ICollection<TSpinoff> TSpinoffs { get; set; } = new List<TSpinoff>();
}