// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppTestMovieEF.Models;

[Table("T_Spinoff")]
public partial class TSpinoff
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    [Display(Name = "Nome")]
    public string Spinoff { get; set; }

    [Display(Name = "Data di Uscita")]
    public DateOnly? Data { get; set; }

    [Column("isCanonical")]
    [Display(Name = "E' Canonico")]
    public bool? IsCanonical { get; set; }

    [Column("idMovie")]
    [Display(Name = "Film di Appartenenza")]

    public int? IdMovie { get; set; }

    [ForeignKey("IdMovie")]
    [InverseProperty("TSpinoffs")]
    [Display(Name = "Film di Appartenenza")]

    public virtual TMovie IdMovieNavigation { get; set; }
}